# Generated by Django 3.2.6 on 2021-09-04 12:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('info', models.TextField()),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent_section', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rfp.section')),
            ],
            options={
                'ordering': ('-updated',),
            },
        ),
    ]
