# Generated by Django 3.2.6 on 2021-09-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfp', '0002_alter_section_parent_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='info',
            field=models.TextField(blank=True),
        ),
    ]
