# Generated by Django 3.2.6 on 2021-09-04 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfp', '0003_alter_section_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='parent_section',
            new_name='parentsection',
        ),
    ]
