# Generated by Django 3.2.6 on 2021-09-05 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfp', '0004_rename_parent_section_section_parentsection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('updated',)},
        ),
    ]
