# Generated by Django 3.2.6 on 2021-09-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('income', 'Income'), ('expenditure', 'Expenditure')], default='expenditure', max_length=12),
        ),
    ]
