# Generated by Django 3.2.6 on 2021-09-28 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='type',
        ),
    ]
